#!/usr/bin/env bash
Input_Path=$1
if [ ${#@} -lt 1 ];then
    Input_Path="."
fi
cd ${Input_Path}

function Print_Dir_File() {
    local Dir_argv
    Dir_argv=$1
    for list in `ls ${Dir_argv}`
    do
        if [ -d ${Dir_argv}/${list} ];then
            Print_Dir_File ${Dir_argv}/${list}
        else
            echo "${Dir_argv}/${list}"
        fi
    done
}

Print_Dir_File "${Input_Path}"
